Мазур Наталья Игоревна Т120-101М-20

In [1]:
import numpy as np

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [2]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Поменять 2 строки в матрице

In [3]:
A = np.random.randint(5,size=(5,4))
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[0 2 3 4]
 [4 2 3 3]
 [3 3 2 1]
 [0 2 2 2]
 [1 1 4 4]]
[[4 2 3 3]
 [0 2 3 4]
 [3 3 2 1]
 [0 2 2 2]
 [1 1 4 4]]


Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [4]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 28) ( 4, 92) ( 5,  8) ( 5, 32) ( 7,  9) ( 7, 37) ( 8, 32) ( 9, 37)
 (11, 50) (11, 58) (12, 70) (12, 97) (13, 15) (13, 72) (15, 72) (17, 39)
 (17, 91) (21, 41) (21, 46) (27, 47) (27, 91) (28, 92) (37, 72) (37, 89)
 (39, 91) (41, 46) (47, 91) (50, 58) (70, 97) (72, 89)]


Дан массив C; создать массив A, что np.bincount(A) == C

In [5]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)
print(A)
print(np.bincount(A))

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]
[0 2 1 1 2 0 1]


Посчитать среднее, используя плавающее окно

In [6]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [7]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [8]:
arr = np.random.randint(0,2,5)
print(arr)
np.logical_not(arr, out=arr)
print(arr)

brr = np.random.randint(1,2,5)
print(brr)
np.negative(brr, out=brr)
print(brr)

[0 1 1 0 0]
[1 0 0 1 1]
[1 1 1 1 1]
[-1 -1 -1 -1 -1]


Посчитать ранг матрицы

In [9]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)

Найти наиболее частое значение в массиве

In [10]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [11]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 1 3]
   [1 4 0]
   [4 1 4]]

  [[1 3 4]
   [4 0 2]
   [1 4 4]]

  [[3 4 1]
   [0 2 3]
   [4 4 1]]

  [[4 1 4]
   [2 3 0]
   [4 1 4]]

  [[1 4 4]
   [3 0 0]
   [1 4 3]]

  [[4 4 2]
   [0 0 1]
   [4 3 3]]

  [[4 2 1]
   [0 1 3]
   [3 3 1]]

  [[2 1 1]
   [1 3 1]
   [3 1 4]]]


 [[[1 4 0]
   [4 1 4]
   [4 0 0]]

  [[4 0 2]
   [1 4 4]
   [0 0 3]]

  [[0 2 3]
   [4 4 1]
   [0 3 3]]

  [[2 3 0]
   [4 1 4]
   [3 3 2]]

  [[3 0 0]
   [1 4 3]
   [3 2 2]]

  [[0 0 1]
   [4 3 3]
   [2 2 1]]

  [[0 1 3]
   [3 3 1]
   [2 1 1]]

  [[1 3 1]
   [3 1 4]
   [1 1 0]]]


 [[[4 1 4]
   [4 0 0]
   [3 1 2]]

  [[1 4 4]
   [0 0 3]
   [1 2 2]]

  [[4 4 1]
   [0 3 3]
   [2 2 0]]

  [[4 1 4]
   [3 3 2]
   [2 0 2]]

  [[1 4 3]
   [3 2 2]
   [0 2 3]]

  [[4 3 3]
   [2 2 1]
   [2 3 0]]

  [[3 3 1]
   [2 1 1]
   [3 0 0]]

  [[3 1 4]
   [1 1 0]
   [0 0 4]]]


 [[[4 0 0]
   [3 1 2]
   [3 3 3]]

  [[0 0 3]
   [1 2 2]
   [3 3 3]]

  [[0 3 3]
   [2 2 0]
   [3 3 1]]

  [[3 3 2]
   [2 0 2]
   [3 1 4]]

  [[3 2 2]
   

Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [12]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


Дан массив 16x16, посчитать сумму по блокам 4x4

In [13]:
Z = np.ones((16,16))
print(Z)
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], 4), axis=0),
                                       np.arange(0, Z.shape[1], 4), axis=1)
print(S)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


Найти n наибольших значений в массиве

In [14]:
n=5
Z = np.random.randint(0,10,size=10)
print(Z)
print (Z[np.argpartition(-Z,n)[:n]])

[5 7 7 8 5 9 0 5 4 3]
[8 9 7 7 5]


Построить прямое произведение массивов (все комбинации с каждым элементом)

In [15]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [16]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 6 7]


Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [17]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[2 0 1]
 [3 0 4]
 [1 2 2]
 [0 1 4]
 [4 4 3]
 [3 0 3]
 [1 3 4]
 [2 1 0]
 [0 1 0]
 [3 2 2]]
[[2 0 1]
 [3 0 4]
 [1 2 2]
 [0 1 4]
 [4 4 3]
 [3 0 3]
 [1 3 4]
 [2 1 0]
 [0 1 0]
 [3 2 2]]


Преобразовать вектор чисел в матрицу бинарных представлений

In [18]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


Дан двумерный массив. Найти все различные строки

In [19]:
Z = np.random.randint(0, 2, (3,3))
print(Z)
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [1 0 1]
 [0 0 1]]
[[0 0 1]
 [1 0 1]]


Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [20]:
# создаем массив А 
A = np.random.randint(1,5,5)
print(A)
# создаем массив Б
B = np.random.randint(1,5,5)
print(B)
print(np.einsum('i,i', A, np.ones(5)) )     # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j', A, B))    # np.outer(A, B)

[2 4 3 3 1]
[2 3 3 4 1]
13.0
[ 4 12  9 12  1]
38
[[ 4  6  6  8  2]
 [ 8 12 12 16  4]
 [ 6  9  9 12  3]
 [ 6  9  9 12  3]
 [ 2  3  3  4  1]]
