Мазур Наталья Игоревна Т120-101М-20

Импортировать NumPy под именем np

In [1]:
import numpy as np

Напечатать версию и конфигурацию

In [2]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный единицами

In [4]:
Z = np.ones(10)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать вектор размера 10, заполненный числом 2.5

In [5]:
Z = np.full(10, 2.5)
print(Z)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Как получить документацию о функции numpy.add из командной строки?
python3 -c "import numpy; numpy.info(numpy.add)"

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Создать вектор со значениями от 10 до 49

In [8]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Развернуть вектор (первый становится последним)

In [9]:
Z = np.arange(50)
Z = Z[::-1]

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [10]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [11]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


Создать массив 3x3x3 со случайными значениями

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.59322295 0.10063893 0.31477265]
  [0.73418189 0.33685299 0.16768167]
  [0.82698413 0.110288   0.56432745]]

 [[0.65312528 0.60574693 0.61064898]
  [0.88041637 0.99575357 0.58113857]
  [0.38577814 0.64181289 0.51498289]]

 [[0.24268228 0.21358572 0.76846273]
  [0.51233119 0.97069989 0.36947053]
  [0.32173454 0.28311637 0.90841473]]]


Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0040960691215296 0.9916879489056729


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4921090673780361


Создать матрицу с 0 внутри, и 1 на границах

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0

Выяснить результат следующих выражений

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

False

Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [17]:
Z = np.diag(np.arange(1, 5), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Создать 8x8 матрицу и заполнить её в шахматном порядке

In [18]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [19]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [20]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
