Мазур Наталья Игоревна Т120-101М-20

In [1]:
import numpy as np

Перемножить матрицы 5x3 и 3x2

In [2]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1

Создать 5x5 матрицу со значениями в строках от 0 до 4

In [4]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Есть генератор, сделать с его помощью массив

In [5]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [6]:
Z = np.linspace(0,1,12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Отсортировать вектор

In [7]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.07316205 0.103195   0.16897284 0.57128149 0.61198112 0.70533074
 0.77565372 0.85273372 0.92391436 0.94656481]


Проверить, одинаковы ли 2 numpy массива

In [8]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


Сделать массив неизменяемым

In [9]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1 - выдаст ошибку

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [10]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.94924962 0.72447741 0.61965608 1.26752962 0.67316689 0.98933566
 0.80407077 1.32409561 1.17328202 0.89163045]
[1.22173044 0.40525658 1.42662119 0.70959457 0.1214015  1.35808728
 0.36560022 0.77862611 0.91490577 1.38702567]


Заменить максимальный элемент на ноль

In [11]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.05872518 0.38024877 0.60285935 0.94271949 0.46946494 0.
 0.34688711 0.71615654 0.96302244 0.95413753]


Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [12]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [13]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [14]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


Напечатать все значения в массиве

In [15]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

Найти ближайшее к заданному значению число в заданном массиве

In [16]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

60


Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [17]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-17-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [18]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.4993331  0.95800632 0.53667143 0.73727474 0.80577027
  0.61013762 0.79816435 0.69520268 0.50246577]
 [0.4993331  0.         0.46609505 0.32102142 0.32874567 0.41554241
  0.16258138 0.34158112 0.56447897 0.38374879]
 [0.95800632 0.46609505 0.         0.55362253 0.30795935 0.51376136
  0.3555394  0.36902681 0.69615659 0.64300296]
 [0.53667143 0.32102142 0.55362253 0.         0.25465134 0.72370932
  0.24435223 0.62061552 0.24443894 0.08981229]
 [0.73727474 0.32874567 0.30795935 0.25465134 0.         0.61984435
  0.16634508 0.48566806 0.39507347 0.34143001]
 [0.80577027 0.41554241 0.51376136 0.72370932 0.61984435 0.
  0.49603535 0.14700028 0.95811085 0.79554116]
 [0.61013762 0.16258138 0.3555394  0.24435223 0.16634508 0.49603535
  0.         0.38064134 0.46423866 0.32955123]
 [0.79816435 0.34158112 0.36902681 0.62061552 0.48566806 0.14700028
  0.38064134 0.         0.84428202 0.69983385]
 [0.69520268 0.56447897 0.69615659 0.24443894 0.39507347 0.95811085
  0.46423866 0.84428

Преобразовать массив из float в int

In [19]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

Дан файл:
1,2,3,4,5
6,,,7,8
,,9,10,11
Как прочитать его?

In [20]:
import tempfile
tf = tempfile.NamedTemporaryFile()
tf.write(b"1,2,3,4,5\n6,,,7,8\n,,9,10,11\n")
tf.flush()

Z = np.genfromtxt(tf.name, delimiter=",")
print(Z)

tf.close()

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


Каков эквивалент функции enumerate для numpy массивов?

In [21]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


Сформировать 2D массив с распределением Гаусса

In [22]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.hypot(X, Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

Случайно расположить p элементов в 2D массив

In [23]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


Отнять среднее из каждой строки в матрице

In [24]:
X = np.random.rand(5, 10)
print(X)
Y = X - X.mean(axis=1, keepdims=True)
print(Z)

[[0.68086598 0.43463341 0.45543398 0.74721664 0.07519213 0.60606263
  0.75008923 0.71532685 0.5248348  0.34486312]
 [0.07962381 0.57187477 0.99538366 0.13208881 0.22092928 0.60648218
  0.77055196 0.40224103 0.47397757 0.00179733]
 [0.57726352 0.82999871 0.57819122 0.81355646 0.52895169 0.23717897
  0.93710737 0.48704606 0.34601704 0.27620603]
 [0.55810864 0.99469999 0.03549159 0.90709472 0.45319192 0.37945266
  0.28022605 0.78387334 0.92857403 0.31439764]
 [0.73539486 0.26337154 0.08960517 0.9024929  0.31748549 0.54929551
  0.69393727 0.00735863 0.29766088 0.36026017]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


Отсортировать матрицу по n-ому столбцу

In [25]:
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[9 3 4]
 [2 9 3]
 [4 5 9]]
[[9 3 4]
 [4 5 9]
 [2 9 3]]


Определить, есть ли в 2D массиве нулевые столбцы

In [26]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [27]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 1. 2. 3. 3. 2. 4. 6. 4. 3.]


Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [33]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


Дан четырехмерный массив, посчитать сумму по последним двум осям

In [29]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[66 55 62 41]
 [54 63 46 48]
 [56 53 49 46]]


Найти диагональные элементы произведения матриц

In [43]:
A = np.random.randint(10, size=(3, 3))
print("A")
print(A)
B = np.random.randint(10, size=(3, 3))
print("B")
print(B)
C = np.dot(A, B)
print("C")
print(C)
print("diag")
print(np.diag(C))

A
[[8 0 0]
 [5 5 2]
 [5 5 8]]
B
[[6 5 5]
 [5 2 6]
 [2 9 5]]
C
[[ 48  40  40]
 [ 59  53  65]
 [ 71 107  95]]
diag
[48 53 95]
